baseURL = "https://zarva.me/"
languageCode = "en-us"
title = "Test Title"
enableRobotsTXT = true
defaultContentLanguage = "en"

[languages]
  [languages.en]
    title = "zarva.me"
    weight = 1
  [languages.de]
    title = "zarva.me"
    weight = 2
    [languages.de.params]
      [languages.de.params.navigation]
        help = "Hilfe"
  [languages.ru]
    title = "zarva.me"
    weight = 3
    [languages.ru.params]
      [languages.ru.params.navigation]
        help = "Помощь"


[params]
  favicon = "/dist/img/favicon.ico"
  help = "help"
