name: Main
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.61.0'

      - name: Build
        run: |
          cd src
          npm run build:production
          cd ..
          HUGO_ENV="production" hugo --minify

      - name: Build $ Publish
        uses: lbejiuk/adip@v1
        with:
          TOKEN: ${{secrets.token}}
          PACKAGE_REPOSITORY: 'private_pkg'
