name: Main
on:
  push:
    branches:
      - master

jobs:
  buildAndPublish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.61.0'

      - name: Build
        run: |
          cd src
          npm i
          npm run build:production
          cd ..
          HUGO_ENV="production" hugo --minify

      - name: Build $ Publish
        uses: lbejiuk/adip@v1
        with:
          TOKEN: ${{secrets.token}}
          PACKAGE_REPOSITORY: 'private_pkg'

  deploy:
    name: Deploy on server
    runs-on: ubuntu-latest
    needs: buildAndPublish
    steps:
      - name: Deploy on server
        run: |
          IMAGE_VERSION=$(echo "${{ github.sha }}" | cut -c 1-12)
          SERVICE_NAME=zarva_me_zarva_me
          IMAGE_NAME=zarva_me
          curl "https://zarva.me:9999/service/update?serviceName=$SERVICE_NAME&imageName=$IMAGE_NAME&imageVersion=$IMAGE_VERSION&token=${{ secrets.updaterToken }}" -v -f
